[tool.black]
line-length = 100
target-version = ["py311"]
include = "\.(py|pyi)$"
exclude = [
  "^/data/",
  "^/logs/",
  "^/.*__pycache__",
]

[tool.ruff]
line-length = 100
target-version = "py311"
extend-exclude = [
  "data",
  "logs",
  "**/__pycache__",
]
select = [
  "E",  # pycodestyle (errors)
  "F",  # pyflakes
  "I",  # isort
]
ignore = []
fix = true

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"
